language: node_js
node_js:
  - '13.11.0'
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
jobs:
  include:
    # all branches
    - stage: Lint, Test, & Build
      script:
        - yarn lint
        - yarn test-ci
        - yarn build
    # master branch only
    - stage: master branch - Build the package, build and publish docs, semantic-release, and upload coverage
      if: branch = master
      script:
        - yarn build
        - yarn build-docs
        - npx semantic-release
      deploy:
        # Deploy most recent docs build to gh-pages branch
        - provider: pages
          local_dir: docs/
          github_token: $GH_TOKEN
          skip_cleanup: true
        # Deploy most recent docs build to master branch
        - provider: script
          script: sh bin/travisDeployDocs.sh
          skip_cleanup: true
      after_success:
        # Build and upload test coverage reports after every successful commit to master
        - npm install -g codecov
        - yarn cover --maxWorkers=$(nproc)
        - bash <(curl -s https://codecov.io/bash)
