language: node_js
node_js:
  - '13.9.0'
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
branches:
  only:
    - master
    - production
    - staging
    - /^v[0-9]+.*$/
jobs:
  include:
    - stage: Lint, Test, & Build
      script:
        - yarn lint
        - yarn test-ci
        - yarn build
    - stage: Build, Publish Docs, & Release
      if: branch = master
      script:
        - yarn build
        - yarn build-docs
        - npx semantic-release
      deploy:
        # Deploy built Production Documentation to gh-pages branch
        - provider: pages
          skip_cleanup: true
          local_dir: docs/
          github_token: $GH_TOKEN
          on:
            branch: master
        # Deploy latest docs build to master branch
        - provider: script
          skip_cleanup: true
          script: sh bin/travisDeployDocs.sh
          on:
            branch: master
      after_success:
        # Upload test coverage reports
        - npm install -g codecov
        - yarn cover --maxWorkers=$(nproc)
        - bash <(curl -s https://codecov.io/bash)
