language: node_js
node_js:
  - '13.9.0'
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - npm install -g codecov
  - yarn
jobs:
  include:
    - stage: Lint, Build, and Test
      script:
        - yarn lint
        - yarn test
        - yarn build
    - stage: NPM/Yarn Release
      script: yarn release
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
          branch: master
branches:
  only:
    - master
    - staging
    - /^v[0-9]+.*$/
after_success:
- yarn cover --maxWorkers=$(nproc)
- bash <(curl -s https://codecov.io/bash)