language: node_js
node_js:
  - '13.9.0'
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
jobs:
  include:
    - stage: Lint, Build, and Test
      script:
        - yarn lint
        - yarn test
        - yarn build
    - stage: NPM/Yarn Release
      if: tag IS present
      script: yarn build
      deploy:
        - provider: npm
          email: '$NPM_EMAIL'
          api_key: '$NPM_TOKEN'
          skip_cleanup: true
          on:
            tags: true
            branch: master
          after_success:
            - npm install -g codecov
            - yarn cover --maxWorkers=$(nproc)
            - bash <(curl -s https://codecov.io/bash)
        - provider: releases
            api_key: '$GITHUB_TOKEN'
            file_glob: true
            file: dist/**/*
            skip_cleanup: true
            on:
              tags: true