language: node_js
node_js:
  - '13.9.0'
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
branches:
  only:
    - master
    - production
    - staging
    - /^v[0-9]+.*$/
jobs:
  include:
    - stage: Lint, Build, and Test
      script:
        - yarn lint
        - yarn test-ci
        - yarn build
    - stage: Build & publish
      if: branch = master
      script:
      - npm run build
      - npx semantic-release
      after_success:
        - npm install -g codecov
        - yarn cover --maxWorkers=$(nproc)
        - bash <(curl -s https://codecov.io/bash)