codecov:
  token: secret:cwRQpVfLrryRJrcW4mVt6E+wnKZw06fNb3Kv+N+EzYiEG+ERwXJ6Dq3Hl0N1qhDPKjhPW+oOPHEwLGwT7kmWt4TqGVWXIaWkVKgjQxqq4LzgvYojJRWlqPfyztszqH55
  bot: ShaggyTech
  ci:
    - "travis.org"
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        paths: 
          - "src"
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no