name: setup
description: "Setup (Dependencies, Nodejs)"

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2.4.0

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install
