const data = {
  Count: 136,
  Message:
    'Results returned successfully. NOTE: Any missing decoded values should be interpreted as NHTSA does not have data on the specific variable. Missing value should NOT be interpreted as an indication that a feature or technology is unavailable for a vehicle.',
  SearchCriteria: 'VIN(s): WVWKG61J34D132375',
  Results: [
    {
      // Add in our mocked data indicator
      Mocked: 'DecodeVinValuesExtended',
      MockedData:
        'axios is being mocked from actions/DecodeVinValuesExtended/__mocks__/axios',
      // Standard NHSTA response follows:
      ABS: '',
      ActiveSafetySysNote: '',
      AdaptiveCruiseControl: '',
      AdaptiveDrivingBeam: '',
      AdaptiveHeadlights: '',
      AdditionalErrorText: '',
      AirBagLocCurtain: '',
      AirBagLocFront: '1st Row (Driver & Passenger)',
      AirBagLocKnee: '',
      AirBagLocSeatCushion: '',
      AirBagLocSide: '1st Row (Driver & Passenger)',
      AutoReverseSystem: '',
      AutomaticPedestrianAlertingSound: '',
      AxleConfiguration: '',
      Axles: '',
      BasePrice: '',
      BatteryA: '',
      BatteryA_to: '',
      BatteryCells: '',
      BatteryInfo: '',
      BatteryKWh: '',
      BatteryKWh_to: '',
      BatteryModules: '',
      BatteryPacks: '',
      BatteryType: '',
      BatteryV: '',
      BatteryV_to: '',
      BedLengthIN: '',
      BedType: '',
      BlindSpotMon: '',
      BodyCabType: '',
      BodyClass: 'Sport Utility Vehicle (SUV)/Multi-Purpose Vehicle (MPV)',
      BrakeSystemDesc: '',
      BrakeSystemType: '',
      BusFloorConfigType: 'Not Applicable',
      BusLength: '',
      BusType: 'Not Applicable',
      CAN_AACN: '',
      CIB: '',
      CashForClunkers: '',
      ChargerLevel: '',
      ChargerPowerKW: '',
      CoolingType: '',
      CurbWeightLB: '',
      CustomMotorcycleType: 'Not Applicable',
      DaytimeRunningLight: '',
      DestinationMarket: '',
      DisplacementCC: '2979.1682352',
      DisplacementCI: '181.8',
      DisplacementL: '3.0',
      Doors: '4',
      DriveType: '',
      DriverAssist: '',
      DynamicBrakeSupport: '',
      EDR: '',
      ESC: '',
      EVDriveUnit: '',
      ElectrificationLevel: '',
      EngineConfiguration: '',
      EngineCycles: '',
      EngineCylinders: '6',
      EngineHP: '300',
      EngineHP_to: '',
      EngineKW: '223.7100',
      EngineManufacturer: '',
      EngineModel: '',
      EntertainmentSystem: '',
      ErrorCode: '6',
      ErrorText: '6 - Incomplete VIN',
      ForwardCollisionWarning: '',
      FuelInjectionType: '',
      FuelTypePrimary: 'Gasoline',
      FuelTypeSecondary: '',
      GCWR: '',
      GCWR_to: '',
      GVWR: 'Class 1D: 5,001 - 6,000 lb (2,268 - 2,722 kg)',
      GVWR_to: '',
      KeylessIgnition: '',
      LaneDepartureWarning: '',
      LaneKeepSystem: '',
      LowerBeamHeadlampLightSource: '',
      Make: 'BMW',
      Manufacturer: 'BMW MANUFACTURER CORPORATION / BMW NORTH AMERICA',
      ManufacturerId: '968',
      Model: 'X3',
      ModelYear: '2011',
      MotorcycleChassisType: 'Not Applicable',
      MotorcycleSuspensionType: 'Not Applicable',
      NCSABodyType:
        'Compact Utility (Utility Vehicle Categories "Small" and "Midsize")',
      NCSAMake: 'BMW',
      NCSAMapExcApprovedBy: '',
      NCSAMapExcApprovedOn: '',
      NCSAMappingException: '',
      NCSAModel: 'X3',
      NCSANote: '',
      Note: '',
      OtherBusInfo: '',
      OtherEngineInfo: '',
      OtherMotorcycleInfo: '',
      OtherRestraintSystemInfo:
        'Head Inflatable Restraint for Driver, Front Passenger, Rear Outboard Driver-side and Rear Outboard Passenger-side.  Knee Inflatable Restraint for Driver.  Pretensioners for Driver and Front Passenger.',
      OtherTrailerInfo: '',
      ParkAssist: '',
      PedestrianAutomaticEmergencyBraking: '',
      PlantCity: 'MUNICH',
      PlantCompanyName: '',
      PlantCountry: 'GERMANY',
      PlantState: '',
      PossibleValues: '',
      Pretensioner: 'Yes',
      RearCrossTrafficAlert: '',
      RearVisibilitySystem: '',
      SAEAutomationLevel: '',
      SAEAutomationLevel_to: '',
      SeatBeltsAll: 'Manual',
      SeatRows: '',
      Seats: '',
      SemiautomaticHeadlampBeamSwitching: '',
      Series: 'X3',
      Series2: '',
      SteeringLocation: '',
      SuggestedVIN: '',
      TPMS: 'Direct',
      TopSpeedMPH: '',
      TrackWidth: '',
      TractionControl: '',
      TrailerBodyType: 'Not Applicable',
      TrailerLength: '',
      TrailerType: 'Not Applicable',
      TransmissionSpeeds: '',
      TransmissionStyle: '',
      Trim: 'xDrive35i',
      Trim2: 'SAV',
      Turbo: '',
      VIN: '5UXWX7C5*BA',
      ValveTrainDesign: '',
      VehicleType: 'MULTIPURPOSE PASSENGER VEHICLE (MPV)',
      WheelBaseLong: '',
      WheelBaseShort: '',
      WheelBaseType: '',
      WheelSizeFront: '',
      WheelSizeRear: '',
      Wheels: '',
      Windows: ''
    }
  ]
}

module.exports.data = data
