export default {
  mocked: true,
  FetchResponse: {
    headers: 'mocked-headers',
    ok: true,
    redirected: false,
    status: 200,
    statusText: 'OK',
    url: 'mocked-url',
  },
  Count: 140,
  Message: 'Results returned successfully.',
  SearchCriteria: 'VIN:3VWD07AJ5EM388202',
  Results: [
    {
      Value: '',
      ValueId: '',
      Variable: 'Suggested VIN',
      VariableId: 142,
    },
    {
      Value: '0',
      ValueId: '0',
      Variable: 'Error Code',
      VariableId: 143,
    },
    {
      Value: '',
      ValueId: '',
      Variable: 'Possible Values',
      VariableId: 144,
    },
    {
      Value: null,
      ValueId: '',
      Variable: 'Additional Error Text',
      VariableId: 156,
    },
    {
      Value: '0 - VIN decoded clean. Check Digit (9th position) is correct',
      ValueId: '',
      Variable: 'Error Text',
      VariableId: 191,
    },
    {
      Value: null,
      ValueId: null,
      Variable: 'Destination Market',
      VariableId: 10,
    },
    {
      Value: 'VOLKSWAGEN',
      ValueId: '482',
      Variable: 'Make',
      VariableId: 26,
    },
    {
      Value: 'VOLKSWAGEN GROUP OF AMERICA, INC.',
      ValueId: '1147',
      Variable: 'Manufacturer Name',
      VariableId: 27,
    },
    {
      Value: 'Jetta',
      ValueId: '3137',
      Variable: 'Model',
      VariableId: 28,
    },
    {
      Value: '2014',
      ValueId: '',
      Variable: 'Model Year',
      VariableId: 29,
    },
    {
      Value: 'PUEBLA',
      ValueId: '',
      Variable: 'Plant City',
      VariableId: 31,
    },
    {
      Value: 'SE',
      ValueId: '',
      Variable: 'Series',
      VariableId: 34,
    },
    {
      Value: null,
      ValueId: '',
      Variable: 'Trim',
      VariableId: 38,
    },
    {
      Value: 'PASSENGER CAR',
      ValueId: '2',
      Variable: 'Vehicle Type',
      VariableId: 39,
    },
    {
      Value: 'MEXICO',
      ValueId: '12',
      Variable: 'Plant Country',
      VariableId: 75,
    },
    {
      Value: null,
      ValueId: '',
      Variable: 'Plant Company Name',
      VariableId: 76,
    },
    {
      Value: null,
      ValueId: '',
      Variable: 'Plant State',
      VariableId: 77,
    },
    {
      Value: null,
      ValueId: '',
      Variable: 'Trim2',
      VariableId: 109,
    },
  ],
};
