const data = {
  Count: 136,
  Message:
    'Results returned successfully. NOTE: Any missing decoded values should be interpreted as NHTSA does not have data on the specific variable. Missing value should NOT be interpreted as an indication that a feature or technology is unavailable for a vehicle.',
  SearchCriteria: 'VIN(s): WVWKG61J34D132375',
  Results: [
    {
      // Add in our mocked data indicator
      Mocked: 'DecodeVinValues',
      MockedData:
        'axios is being mocked from actions/DecodeVinValues/__mocks__/axios',
      // Standard NHSTA response follows:
      ABS: '',
      ActiveSafetySysNote: '',
      AdaptiveCruiseControl: '',
      AdaptiveDrivingBeam: '',
      AdaptiveHeadlights: '',
      AdditionalErrorText: '',
      AirBagLocCurtain: '1st Row (Driver & Passenger)',
      AirBagLocFront: '1st Row (Driver & Passenger)',
      AirBagLocKnee: '',
      AirBagLocSeatCushion: '',
      AirBagLocSide: '1st Row (Driver & Passenger)',
      AutoReverseSystem: '',
      AutomaticPedestrianAlertingSound: '',
      AxleConfiguration: '',
      Axles: '',
      BasePrice: '',
      BatteryA: '',
      BatteryA_to: '',
      BatteryCells: '',
      BatteryInfo: '',
      BatteryKWh: '',
      BatteryKWh_to: '',
      BatteryModules: '',
      BatteryPacks: '',
      BatteryType: '',
      BatteryV: '',
      BatteryV_to: '',
      BedLengthIN: '',
      BedType: 'Not Applicable',
      BlindSpotMon: '',
      BodyCabType: 'Not Applicable',
      BodyClass: 'Hatchback/Liftback/Notchback',
      BrakeSystemDesc: '',
      BrakeSystemType: '',
      BusFloorConfigType: 'Not Applicable',
      BusLength: '',
      BusType: 'Not Applicable',
      CAN_AACN: '',
      CIB: '',
      CashForClunkers: '',
      ChargerLevel: '',
      ChargerPowerKW: '',
      CoolingType: '',
      CurbWeightLB: '',
      CustomMotorcycleType: 'Not Applicable',
      DaytimeRunningLight: '',
      DestinationMarket: 'U.S.',
      DisplacementCC: '3189',
      DisplacementCI: '194.604719918',
      DisplacementL: '3.189000',
      Doors: '2',
      DriveType: '',
      DriverAssist: '',
      DynamicBrakeSupport: '',
      EDR: '',
      ESC: '',
      EVDriveUnit: '',
      ElectrificationLevel: '',
      EngineConfiguration: '',
      EngineCycles: '',
      EngineCylinders: '6',
      EngineHP: '240',
      EngineHP_to: '',
      EngineKW: '178.9680',
      EngineManufacturer: 'Volkswagen',
      EngineModel: '',
      EntertainmentSystem: '',
      ErrorCode: '0',
      ErrorText: '0 - VIN decoded clean. Check Digit (9th position) is correct',
      ForwardCollisionWarning: '',
      FuelInjectionType: '',
      FuelTypePrimary: 'Gasoline',
      FuelTypeSecondary: '',
      GCWR: '',
      GCWR_to: '',
      GVWR: '',
      GVWR_to: '',
      KeylessIgnition: '',
      LaneDepartureWarning: '',
      LaneKeepSystem: '',
      LowerBeamHeadlampLightSource: '',
      Make: 'VOLKSWAGEN',
      Manufacturer: 'VOLKSWAGEN GROUP OF AMERICA, INC.',
      ManufacturerId: '1147',
      Model: 'R32',
      ModelYear: '2004',
      MotorcycleChassisType: 'Not Applicable',
      MotorcycleSuspensionType: 'Not Applicable',
      NCSABodyType: '',
      NCSAMake: '',
      NCSAMapExcApprovedBy: '',
      NCSAMapExcApprovedOn: '',
      NCSAMappingException: '',
      NCSAModel: '',
      NCSANote: '',
      Note: '',
      OtherBusInfo: '',
      OtherEngineInfo:
        '50-St./Can. BIN 9/Lev I emission.   Emissions Certification Test Group: 4VWXV03.2220',
      OtherMotorcycleInfo: '',
      OtherRestraintSystemInfo: 'Active Seat Belt',
      OtherTrailerInfo: '',
      ParkAssist: '',
      PedestrianAutomaticEmergencyBraking: '',
      PlantCity: 'BRATISLAVA',
      PlantCompanyName: '',
      PlantCountry: 'SLOVAKIA',
      PlantState: '',
      PossibleValues: '',
      Pretensioner: '',
      RearCrossTrafficAlert: '',
      RearVisibilitySystem: '',
      SAEAutomationLevel: '',
      SAEAutomationLevel_to: '',
      SeatBeltsAll: 'Manual',
      SeatRows: '',
      Seats: '',
      SemiautomaticHeadlampBeamSwitching: '',
      Series: '',
      Series2: '',
      SteeringLocation: '',
      SuggestedVIN: '',
      TPMS: '',
      TopSpeedMPH: '',
      TrackWidth: '',
      TractionControl: '',
      TrailerBodyType: 'Not Applicable',
      TrailerLength: '',
      TrailerType: 'Not Applicable',
      TransmissionSpeeds: '',
      TransmissionStyle: '',
      Trim: '',
      Trim2: '',
      Turbo: '',
      VIN: 'WVWKG61J34D132375',
      ValveTrainDesign: '',
      VehicleType: 'PASSENGER CAR',
      WheelBaseLong: '',
      WheelBaseShort: '',
      WheelBaseType: '',
      WheelSizeFront: '',
      WheelSizeRear: '',
      Wheels: '',
      Windows: ''
    }
  ]
}

module.exports.data = data
