name: Upload Test Coverage

on:
  push:

jobs:
  upload-test-coverage:
    name: Test and Upload Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Test
        run: pnpm coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # don't add this token to PUBLIC repos or action will fail
          files: ./packages/lib/coverage/coverage-final.json
          name: "Upload Test Coverage" # optional
          fail_ci_if_error: true # optional (default = false)
