# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Master

on:
  pull_request:
    branches:
      - 'master'

jobs:
  lint-test-build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup Node and Install Depedencies
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn --frozen-lockfile

    - name: Lint and Test
      run: |
        yarn lint
        yarn test

    - name: Build Package
      run: yarn build

    - name: Build Docs
      run: yarn build-docs

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        flags: unittests, master, pull # optional